inputWidth = prompt("Enter the width");
inputHeight = prompt("Enter the height");
let width= parseInt(inputWidth);
let height = parseInt(inputHeight);
let area = width * height;
document.write("the width: " +width);
document.write("<br>");
document.write("the height: "+height);
document.write("<br>");
document.write("the area is: " +area);
